<?php

namespace App\Services\Notifications;

use App\Enums\UserRole;
use App\Models\AppNotification;
use App\Models\CreditNote;
use App\Models\DeviceToken;
use App\Models\User;
use Illuminate\Support\Facades\Log;
use Throwable;

final class CreditNotePushNotifier
{
    public const TYPE_CREATED = 'credit_note_created';

    public const TYPE_APPROVED = 'credit_note_approved';

    public const TYPE_REJECTED = 'credit_note_rejected';

    public const TYPE_COMPLETED = 'credit_note_completed';

    public function __construct(
        private readonly FcmHttpClient $fcm = new FcmHttpClient,
    ) {}

    public function notifyCreated(CreditNote $creditNote): void
    {
        $creditNote->loadMissing([
            'dealer:id,firm_name',
            'salesEmployee:id,full_name,reporting_manager_id',
        ]);

        $managerUser = $this->reportingManagerUser($creditNote);
        if ($managerUser === null) {
            return;
        }

        $this->dispatchToUser(
            user: $managerUser,
            creditNote: $creditNote,
            type: self::TYPE_CREATED,
            title: 'New Credit Note',
            body: $this->createdBody($creditNote),
            route: '/manager/credit-notes/'.$creditNote->id,
        );
    }

    public function notifyApproved(CreditNote $creditNote): void
    {
        $this->notifyEmployee(
            creditNote: $creditNote,
            type: self::TYPE_APPROVED,
            title: 'Credit Note Approved',
            body: $this->statusBody($creditNote, 'approved by Sales Manager'),
        );
    }

    public function notifyRejected(CreditNote $creditNote): void
    {
        $role = $creditNote->rejected_by_role ?: 'Sales Manager';
        $this->notifyEmployee(
            creditNote: $creditNote,
            type: self::TYPE_REJECTED,
            title: 'Credit Note Rejected',
            body: $this->statusBody($creditNote, 'rejected by '.$role),
        );
    }

    public function notifyCompleted(CreditNote $creditNote): void
    {
        $this->notifyEmployee(
            creditNote: $creditNote,
            type: self::TYPE_COMPLETED,
            title: 'Credit Note Generated',
            body: $this->statusBody($creditNote, 'generated by Admin'),
        );
    }

    private function notifyEmployee(
        CreditNote $creditNote,
        string $type,
        string $title,
        string $body,
    ): void {
        $creditNote->loadMissing([
            'dealer:id,firm_name',
            'salesEmployee:id,full_name,reporting_manager_id',
            'salesEmployee.user',
        ]);

        $employeeUser = $creditNote->salesEmployee?->user
            ?? User::query()->where('employee_id', $creditNote->sales_employee_id)->first();

        if (! $employeeUser instanceof User) {
            return;
        }

        $this->dispatchToUser(
            user: $employeeUser,
            creditNote: $creditNote,
            type: $type,
            title: $title,
            body: $body,
            route: '/credit-notes/'.$creditNote->id,
        );
    }

    private function createdBody(CreditNote $creditNote): string
    {
        $employee = $creditNote->salesEmployee?->full_name ?: '-';
        $dealer = $creditNote->dealer?->firm_name ?: '-';
        $amount = $this->formatAmount($creditNote);

        return "{$employee} • {$dealer} • {$amount}";
    }

    private function statusBody(CreditNote $creditNote, string $action): string
    {
        $number = $creditNote->credit_note_no ?: 'Credit Note';
        $dealer = $creditNote->dealer?->firm_name ?: '-';
        $amount = $this->formatAmount($creditNote);

        $body = "{$number} for {$dealer} ({$amount}) was {$action}.";
        if ($creditNote->status === CreditNote::STATUS_REJECTED && filled($creditNote->rejection_remark)) {
            $body .= ' Remarks: '.$creditNote->rejection_remark;
        }

        return $body;
    }

    private function formatAmount(CreditNote $creditNote): string
    {
        $amount = (float) $creditNote->amount;
        $formatted = fmod($amount, 1.0) === 0.0
            ? number_format($amount, 0, '.', ',')
            : number_format($amount, 2, '.', ',');

        return '₹'.$formatted;
    }

    private function reportingManagerUser(CreditNote $creditNote): ?User
    {
        $creditNote->loadMissing(['salesEmployee:id,reporting_manager_id']);
        $managerEmployeeId = $creditNote->salesEmployee?->reporting_manager_id;
        if (! $managerEmployeeId) {
            return null;
        }

        return User::query()
            ->where('employee_id', $managerEmployeeId)
            ->where('role', UserRole::Manager->value)
            ->first();
    }

    private function dispatchToUser(
        User $user,
        CreditNote $creditNote,
        string $type,
        string $title,
        string $body,
        string $route,
    ): void {
        try {
            $data = [
                'type' => $type,
                'notification_type' => $type,
                'credit_note_id' => (string) $creditNote->id,
                'employee_id' => (string) ($creditNote->sales_employee_id ?? ''),
                'dealer_id' => (string) ($creditNote->dealer_id ?? ''),
                'dealer_name' => (string) ($creditNote->dealer?->firm_name ?? ''),
                'amount' => (string) $creditNote->amount,
                'status' => (string) $creditNote->status,
                'status_label' => $creditNote->displayStatusLabel(),
                'event_at' => (string) ($creditNote->updated_at?->toIso8601String() ?? now()->toIso8601String()),
                'route' => $route,
                'action' => 'view',
                'channel_id' => FcmHttpClient::CHANNEL_CRITICAL,
                'fullscreen' => '0',
            ];

            AppNotification::query()->create([
                'user_id' => $user->id,
                'order_id' => null,
                'type' => $type,
                'title' => $title,
                'body' => $body,
                'data' => $data,
            ]);

            $tokens = DeviceToken::query()
                ->where('user_id', $user->id)
                ->pluck('token')
                ->unique()
                ->filter()
                ->values()
                ->all();

            if ($tokens === []) {
                return;
            }

            $result = $this->fcm->sendToTokens(
                tokens: $tokens,
                notification: [
                    'title' => $title,
                    'body' => $body,
                ],
                data: $data,
                android: [
                    'notification' => [
                        'channel_id' => FcmHttpClient::CHANNEL_CRITICAL,
                        'notification_priority' => 'PRIORITY_HIGH',
                        'default_sound' => true,
                        'default_vibrate_timings' => true,
                        'sound' => 'default',
                        'click_action' => 'FLUTTER_NOTIFICATION_CLICK',
                    ],
                ],
            );

            if ($result['invalid_tokens'] !== []) {
                DeviceToken::query()
                    ->whereIn('token', $result['invalid_tokens'])
                    ->delete();
            }
        } catch (Throwable $e) {
            Log::warning('Credit note push notify failed: '.$e->getMessage(), [
                'credit_note_id' => $creditNote->id,
                'type' => $type,
                'user_id' => $user->id,
            ]);
        }
    }
}
