<?php

namespace App\Http\Controllers;

use App\Models\Dealer;
use App\Support\MaharashtraGeography;
use Illuminate\Http\Request;

class DealerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $dealers = Dealer::latest()->paginate(10);

        return view('dealers.index', compact('dealers'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('dealers.create', [
            'state' => MaharashtraGeography::STATE_NAME,
            'districts' => MaharashtraGeography::districts(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'firm_name' => 'required|max:255',
            'assigned_employee_id' => 'required|exists:employees,id',
            'mobile' => ['required', 'regex:/^[6-9][0-9]{9}$/'],
            'state' => MaharashtraGeography::stateRules(),
            'district' => MaharashtraGeography::districtRules(),
            'taluka' => MaharashtraGeography::talukaRules(),
            'village' => 'required|max:255',
            'owner_name' => 'nullable|max:255',
            'email' => 'nullable|email',
            'gst_no' => 'nullable|max:20',
            'pan_no' => 'nullable|max:20',
            'fertilizer_license_no' => 'nullable|max:255',
            'address' => 'nullable',
            'pincode' => ['nullable', 'regex:/^[1-9][0-9]{5}$/'],
            'credit_limit' => 'nullable|numeric|min:0',
            'opening_balance' => 'nullable|numeric|min:0',
            'opening_balance_type' => 'nullable|in:debit,credit',
            'opening_balance_date' => 'nullable|date',
            'outstanding' => 'nullable|numeric|min:0',
            'latitude' => 'nullable|numeric|between:-90,90',
            'longitude' => 'nullable|numeric|between:-180,180',
            'dealer_type' => 'nullable|in:Distributor,Retailer,Wholesaler',
            'status' => 'nullable|boolean',
        ]);

        $validated['outstanding'] = $validated['outstanding'] ?? 0;
        $validated['credit_limit'] = $validated['credit_limit'] ?? 0;
        $validated['opening_balance'] = $validated['opening_balance'] ?? 0;
        $validated['opening_balance_type'] = $validated['opening_balance_type'] ?? 'debit';
        $validated['status'] = $validated['status'] ?? true;
        $validated['dealer_type'] = $validated['dealer_type'] ?? 'Retailer';
        $validated = MaharashtraGeography::canonicalizeLocationFields($validated);

        // dealer_code is auto-generated by the Dealer model (D001, D002, …).
        Dealer::create($validated);

        return redirect()->route('dealers.index')
            ->with('success', 'Dealer Created Successfully.');
    }

    /**
     * Display the specified resource.
     */
    public function show(Dealer $dealer)
    {
        return view('dealers.show', compact('dealer'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Dealer $dealer)
    {
        return view('dealers.edit', compact('dealer'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Dealer $dealer)
    {
        $validated = $request->validate([
            'firm_name' => 'required|max:255',
            'assigned_employee_id' => 'required|exists:employees,id',
            'mobile' => ['required', 'regex:/^[6-9][0-9]{9}$/'],
            'state' => MaharashtraGeography::stateRules(),
            'district' => MaharashtraGeography::districtRules(),
            'taluka' => MaharashtraGeography::talukaRules(),
            'village' => 'required|max:255',
            'owner_name' => 'nullable|max:255',
            'email' => 'nullable|email',
            'gst_no' => 'nullable|max:20',
            'pan_no' => 'nullable|max:20',
            'fertilizer_license_no' => 'nullable|max:255',
            'address' => 'nullable',
            'pincode' => ['nullable', 'regex:/^[1-9][0-9]{5}$/'],
            'credit_limit' => 'nullable|numeric|min:0',
            'opening_balance' => 'nullable|numeric|min:0',
            'opening_balance_type' => 'nullable|in:debit,credit',
            'opening_balance_date' => 'nullable|date',
            'outstanding' => 'nullable|numeric|min:0',
            'latitude' => 'nullable|numeric|between:-90,90',
            'longitude' => 'nullable|numeric|between:-180,180',
            'dealer_type' => 'nullable|in:Distributor,Retailer,Wholesaler',
            'status' => 'nullable|boolean',
        ]);

        // Never allow dealer_code to change on edit.
        unset($validated['dealer_code']);
        $validated = MaharashtraGeography::canonicalizeLocationFields($validated);

        $dealer->update($validated);

        return redirect()->route('dealers.index')
            ->with('success', 'Dealer Updated Successfully.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Dealer $dealer)
    {
        try {
            app(\App\Services\SafeDelete\SafeDeleteGuard::class)->assertCanDelete($dealer);
        } catch (\Illuminate\Validation\ValidationException $exception) {
            $message = $exception->errors()['delete'][0]
                ?? 'Cannot delete this dealer because it is already used in the system. You can deactivate it instead.';

            return redirect()->back()->with('error', $message);
        }

        $dealer->delete();

        return redirect()->route('dealers.index')
            ->with('success', 'Dealer Deleted Successfully.');
    }
}
